<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ServiceDefaults\RestoPulse.ServiceDefaults.csproj" />
    <ProjectReference Include="..\OrderService\RestoPulse.OrderService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Api\Endpoints\" />
    <Folder Include="Api\Validators\" />
    <Folder Include="Application\Commands\" />
    <Folder Include="Application\Mappings\" />
    <Folder Include="Application\Queries\" />
    <Folder Include="Contracts\" />
    <Folder Include="Domains\Entities\" />
    <Folder Include="Domains\Enums\" />
    <Folder Include="Domains\Events\" />
    <Folder Include="Infrastructure\Messaging\" />
    <Folder Include="Infrastructure\Persistence\Migrations\" />
  </ItemGroup>

</Project>
